"""accounts room tables

Revision ID: 23cb430bcaed
Revises: 337c3b11808a
Create Date: 2026-07-10 00:55:26.648172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cb430bcaed'
down_revision: Union[str, None] = '337c3b11808a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_registry_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('ai_platform', 'comms_platform', 'payment', 'hosting', 'domain', 'government', 'banking', 'tool', 'other', name='account_category'), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('linked_api', sa.String(length=255), nullable=False),
    sa.Column('documentation_url', sa.String(length=1000), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_account_registry_entry_created_by_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_registry_entry')),
    schema='accounts'
    )
    op.create_table('api_monitor_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('linked_account_registry_id', sa.String(), nullable=True),
    sa.Column('credit_remaining', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('usage_current_period', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('health_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='api_health_status'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_registry_id'], ['accounts.account_registry_entry.id'], name=op.f('fk_api_monitor_entry_linked_account_registry_id_account_registry_entry'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_monitor_entry')),
    schema='accounts'
    )
    op.create_table('financial_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('subscription', 'salary', 'contractor', 'api_usage', 'hosting', 'other', name='financial_record_category'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('incurred_at', sa.Date(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_period', sa.String(length=50), nullable=False),
    sa.Column('linked_account_registry_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_financial_record_created_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_account_registry_id'], ['accounts.account_registry_entry.id'], name=op.f('fk_financial_record_linked_account_registry_id_account_registry_entry'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_record')),
    schema='accounts'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_record', schema='accounts')
    op.drop_table('api_monitor_entry', schema='accounts')
    op.drop_table('account_registry_entry', schema='accounts')
    # ### end Alembic commands ###
