"""core schema tables

Revision ID: 337c3b11808a
Revises: cb27bf973d3c
Create Date: 2026-07-10 00:39:13.028025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '337c3b11808a'
down_revision: Union[str, None] = 'cb27bf973d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.Enum('staff', 'client', 'system', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='core'
    )
    op.create_index(op.f('ix_core_audit_log_action'), 'audit_log', ['action'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_created_at'), 'audit_log', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False, schema='core')
    op.create_table('calendar_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_fired', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_event')),
    schema='core'
    )
    op.create_index(op.f('ix_core_calendar_event_due_at'), 'calendar_event', ['due_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_calendar_event_remind_at'), 'calendar_event', ['remind_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_calendar_event_room'), 'calendar_event', ['room'], unique=False, schema='core')
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt')),
    schema='core'
    )
    op.create_index(op.f('ix_core_login_attempt_created_at'), 'login_attempt', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_login_attempt_identifier'), 'login_attempt', ['identifier'], unique=False, schema='core')
    op.create_table('room_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_account')),
    schema='core'
    )
    op.create_index('ix_room_account_room', 'room_account', ['room'], unique=True, schema='core')
    op.create_table('staff_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_user')),
    schema='core'
    )
    op.create_index(op.f('ix_core_staff_user_email'), 'staff_user', ['email'], unique=True, schema='core')
    op.create_table('agent_sub_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_account_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_account_id'], ['core.room_account.id'], name=op.f('fk_agent_sub_account_room_account_id_room_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sub_account')),
    schema='core'
    )
    op.create_index('ix_agent_sub_account_room_agent', 'agent_sub_account', ['room_account_id', 'agent_name'], unique=True, schema='core')
    op.create_table('archive_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('shelf', sa.Enum('operational_library', 'transfer', 'receiving', name='archive_shelf'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'received', 'reviewed', 'accepted', 'rejected', 'active', name='archive_item_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=True),
    sa.Column('target_room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=True),
    sa.Column('approved_for_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['core.staff_user.id'], name=op.f('fk_archive_item_reviewed_by_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_item')),
    schema='core'
    )
    op.create_index(op.f('ix_core_archive_item_room'), 'archive_item', ['room'], unique=False, schema='core')
    op.create_index(op.f('ix_core_archive_item_shelf'), 'archive_item', ['shelf'], unique=False, schema='core')
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.Enum('funding', 'customer_transfer', 'agent_spend', 'adjustment', name='ledger_entry_type'), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audit_log_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['core.audit_log.id'], name=op.f('fk_ledger_entry_audit_log_id_audit_log'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entry')),
    schema='core'
    )
    op.create_index(op.f('ix_core_ledger_entry_created_at'), 'ledger_entry', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ledger_entry_entry_type'), 'ledger_entry', ['entry_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ledger_entry_identity_id'), 'ledger_entry', ['identity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ledger_entry_room'), 'ledger_entry', ['room'], unique=False, schema='core')
    op.create_table('refresh_token',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('staff_user_id', sa.String(), nullable=True),
    sa.Column('client_user_id', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['staff_user_id'], ['core.staff_user.id'], name=op.f('fk_refresh_token_staff_user_id_staff_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    schema='core'
    )
    op.create_index(op.f('ix_core_refresh_token_client_user_id'), 'refresh_token', ['client_user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_refresh_token_staff_user_id'), 'refresh_token', ['staff_user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True, schema='core')
    op.create_table('staff_room_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('staff_user_id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('permission', sa.Enum('read', 'write', 'admin', name='room_permission'), nullable=False),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['core.staff_user.id'], name=op.f('fk_staff_room_access_granted_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['core.staff_user.id'], name=op.f('fk_staff_room_access_staff_user_id_staff_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_room_access')),
    schema='core'
    )
    op.create_index(op.f('ix_core_staff_room_access_staff_user_id'), 'staff_room_access', ['staff_user_id'], unique=False, schema='core')
    op.create_index('ix_staff_room_access_user_room', 'staff_room_access', ['staff_user_id', 'room'], unique=True, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staff_room_access_user_room', table_name='staff_room_access', schema='core')
    op.drop_index(op.f('ix_core_staff_room_access_staff_user_id'), table_name='staff_room_access', schema='core')
    op.drop_table('staff_room_access', schema='core')
    op.drop_index(op.f('ix_core_refresh_token_token_hash'), table_name='refresh_token', schema='core')
    op.drop_index(op.f('ix_core_refresh_token_staff_user_id'), table_name='refresh_token', schema='core')
    op.drop_index(op.f('ix_core_refresh_token_client_user_id'), table_name='refresh_token', schema='core')
    op.drop_table('refresh_token', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_room'), table_name='ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_identity_id'), table_name='ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_entry_type'), table_name='ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_created_at'), table_name='ledger_entry', schema='core')
    op.drop_table('ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_archive_item_shelf'), table_name='archive_item', schema='core')
    op.drop_index(op.f('ix_core_archive_item_room'), table_name='archive_item', schema='core')
    op.drop_table('archive_item', schema='core')
    op.drop_index('ix_agent_sub_account_room_agent', table_name='agent_sub_account', schema='core')
    op.drop_table('agent_sub_account', schema='core')
    op.drop_index(op.f('ix_core_staff_user_email'), table_name='staff_user', schema='core')
    op.drop_table('staff_user', schema='core')
    op.drop_index('ix_room_account_room', table_name='room_account', schema='core')
    op.drop_table('room_account', schema='core')
    op.drop_index(op.f('ix_core_login_attempt_identifier'), table_name='login_attempt', schema='core')
    op.drop_index(op.f('ix_core_login_attempt_created_at'), table_name='login_attempt', schema='core')
    op.drop_table('login_attempt', schema='core')
    op.drop_index(op.f('ix_core_calendar_event_room'), table_name='calendar_event', schema='core')
    op.drop_index(op.f('ix_core_calendar_event_remind_at'), table_name='calendar_event', schema='core')
    op.drop_index(op.f('ix_core_calendar_event_due_at'), table_name='calendar_event', schema='core')
    op.drop_table('calendar_event', schema='core')
    op.drop_index(op.f('ix_core_audit_log_entity_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_created_at'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_actor_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_action'), table_name='audit_log', schema='core')
    op.drop_table('audit_log', schema='core')
    # ### end Alembic commands ###
