"""profiles room tables and client auth

Revision ID: 46cdabe19280
Revises: 23cb430bcaed
Create Date: 2026-07-10 07:05:15.294476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cdabe19280'
down_revision: Union[str, None] = '23cb430bcaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id_type', sa.Enum('group', 'member', name='identity_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_identity_created_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['profiles.identity.id'], name=op.f('fk_identity_parent_id_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('path', name=op.f('uq_identity_path')),
    schema='profiles'
    )
    op.create_index('ix_identity_path_pattern', 'identity', ['path'], unique=False, schema='profiles', postgresql_ops={'path': 'text_pattern_ops'})
    op.create_index(op.f('ix_profiles_identity_parent_id'), 'identity', ['parent_id'], unique=False, schema='profiles')
    op.create_table('client_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_client_user_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_user')),
    schema='core'
    )
    op.create_index(op.f('ix_core_client_user_email'), 'client_user', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_client_user_identity_id'), 'client_user', ['identity_id'], unique=False, schema='core')
    op.create_table('consent_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('context', sa.Enum('onboarding', 'record_time', name='consent_context'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('retention_period', sa.String(length=100), nullable=False),
    sa.Column('data_residency', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('captured_by', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['core.staff_user.id'], name=op.f('fk_consent_record_captured_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_consent_record_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_record')),
    schema='profiles'
    )
    op.create_index(op.f('ix_profiles_consent_record_identity_id'), 'consent_record', ['identity_id'], unique=False, schema='profiles')
    op.create_table('permission',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('own_registered', sa.Boolean(), nullable=True),
    sa.Column('own_connected', sa.Boolean(), nullable=True),
    sa.Column('own_auto_respond', sa.Boolean(), nullable=True),
    sa.Column('own_send_on', sa.Boolean(), nullable=True),
    sa.Column('own_can_message_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=True),
    sa.Column('own_can_receive_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=True),
    sa.Column('own_credit_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('own_reply_role', sa.String(length=100), nullable=True),
    sa.Column('own_reply_tone', sa.String(length=100), nullable=True),
    sa.Column('own_reply_complexity', sa.String(length=100), nullable=True),
    sa.Column('own_reply_character', sa.String(length=100), nullable=True),
    sa.Column('own_reply_language', sa.String(length=20), nullable=True),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('effective_registered', sa.Boolean(), nullable=False),
    sa.Column('effective_connected', sa.Boolean(), nullable=False),
    sa.Column('effective_auto_respond', sa.Boolean(), nullable=False),
    sa.Column('effective_send_on', sa.Boolean(), nullable=False),
    sa.Column('effective_can_message_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=False),
    sa.Column('effective_can_receive_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=False),
    sa.Column('effective_credit_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('effective_reply_role', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_tone', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_complexity', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_character', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_language', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_permission_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_permission')),
    schema='profiles'
    )
    op.create_table('profile_account',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_profile_account_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_profile_account')),
    schema='profiles'
    )
    # ### end Alembic commands ###

    # Now that profiles.identity exists, link the ledger's identity_id
    # column to it with a real FK — it was a plain indexed string when
    # core.ledger_entry was created in Phase A, before this table existed.
    op.create_foreign_key(
        'fk_ledger_entry_identity_id_identity',
        'ledger_entry', 'identity',
        ['identity_id'], ['id'],
        source_schema='core', referent_schema='profiles',
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint('fk_ledger_entry_identity_id_identity', 'ledger_entry', schema='core', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_account', schema='profiles')
    op.drop_table('permission', schema='profiles')
    op.drop_index(op.f('ix_profiles_consent_record_identity_id'), table_name='consent_record', schema='profiles')
    op.drop_table('consent_record', schema='profiles')
    op.drop_index(op.f('ix_core_client_user_identity_id'), table_name='client_user', schema='core')
    op.drop_index(op.f('ix_core_client_user_email'), table_name='client_user', schema='core')
    op.drop_table('client_user', schema='core')
    op.drop_index(op.f('ix_profiles_identity_parent_id'), table_name='identity', schema='profiles')
    op.drop_index('ix_identity_path_pattern', table_name='identity', schema='profiles', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_table('identity', schema='profiles')
    # ### end Alembic commands ###
