"""add translate_languages to meeting

Revision ID: 68206eef95e5
Revises: 9709d283d9be
Create Date: 2026-08-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '68206eef95e5'
down_revision: Union[str, None] = '9709d283d9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default gives every pre-existing Meeting row English-only
    # translation (matches live_translation_default_target_language) so this
    # is a safe, non-breaking default for rows scheduled before per-meeting
    # language selection existed.
    op.add_column(
        'meeting',
        sa.Column(
            'translate_languages',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='["en"]',
        ),
        schema='meeting_room',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'translate_languages', schema='meeting_room')
    # ### end Alembic commands ###
