"""collapse_staff_admin_roles

Revision ID: 6d3da23a22a8
Revises: bda30688bcff
Create Date: 2026-07-13 21:21:08.889936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3da23a22a8'
down_revision: Union[str, None] = 'bda30688bcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_registration_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='client_registration_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_client_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_client_user_id'], ['core.client_user.id'], name=op.f('fk_client_registration_request_created_client_user_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['core.staff_user.id'], name=op.f('fk_client_registration_request_reviewed_by_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_registration_request')),
    schema='core'
    )
    op.create_index(op.f('ix_core_client_registration_request_email'), 'client_registration_request', ['email'], unique=False, schema='core')
    op.create_table('group_invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_client_id', sa.String(), nullable=True),
    sa.Column('created_by_staff_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['core.client_user.id'], name=op.f('fk_group_invite_created_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_group_invite_created_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_group_invite_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_invite')),
    schema='profiles'
    )
    op.create_index(op.f('ix_profiles_group_invite_identity_id'), 'group_invite', ['identity_id'], unique=False, schema='profiles')
    op.create_index(op.f('ix_profiles_group_invite_token'), 'group_invite', ['token'], unique=True, schema='profiles')
    op.create_index('uq_group_invite_active_identity', 'group_invite', ['identity_id'], unique=True, schema='profiles', postgresql_where=sa.text('is_active'))
    op.create_table('member_profile',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('registered_via', sa.String(length=50), nullable=False),
    sa.Column('source_invite_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_member_profile_identity_id_identity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_invite_id'], ['profiles.group_invite.id'], name=op.f('fk_member_profile_source_invite_id_group_invite'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_member_profile')),
    schema='profiles'
    )
    op.drop_index(op.f('ix_core_staff_room_access_staff_user_id'), table_name='staff_room_access', schema='core')
    op.drop_index(op.f('ix_staff_room_access_user_room'), table_name='staff_room_access', schema='core')
    op.drop_table('staff_room_access', schema='core')
    op.drop_column('staff_user', 'is_superadmin', schema='core')
    op.add_column('identity', sa.Column('created_by_client_id', sa.String(), nullable=True), schema='profiles')
    op.create_foreign_key(op.f('fk_identity_created_by_client_id_client_user'), 'identity', 'client_user', ['created_by_client_id'], ['id'], source_schema='profiles', referent_schema='core', ondelete='SET NULL')
    # `room_permission` is now orphaned — nothing references it after
    # staff_room_access is dropped, but autogenerate doesn't detect
    # orphan enum types (it only tracks columns), so this is dropped
    # explicitly.
    op.execute("DROP TYPE IF EXISTS room_permission")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_identity_created_by_client_id_client_user'), 'identity', schema='profiles', type_='foreignkey')
    op.drop_column('identity', 'created_by_client_id', schema='profiles')
    # Historical superadmin-ness is not recoverable — every restored row
    # defaults to False.
    op.add_column('staff_user', sa.Column('is_superadmin', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()), schema='core')
    op.alter_column('staff_user', 'is_superadmin', server_default=None, schema='core')
    op.execute("CREATE TYPE room_permission AS ENUM ('read', 'write', 'admin')")
    op.create_table('staff_room_access',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('staff_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room', postgresql.ENUM('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name', create_type=False), autoincrement=False, nullable=False),
    sa.Column('permission', postgresql.ENUM('read', 'write', 'admin', name='room_permission', create_type=False), autoincrement=False, nullable=False),
    sa.Column('granted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['core.staff_user.id'], name=op.f('fk_staff_room_access_granted_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['core.staff_user.id'], name=op.f('fk_staff_room_access_staff_user_id_staff_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_room_access')),
    schema='core'
    )
    op.create_index(op.f('ix_staff_room_access_user_room'), 'staff_room_access', ['staff_user_id', 'room'], unique=True, schema='core')
    op.create_index(op.f('ix_core_staff_room_access_staff_user_id'), 'staff_room_access', ['staff_user_id'], unique=False, schema='core')
    op.drop_table('member_profile', schema='profiles')
    op.drop_index('uq_group_invite_active_identity', table_name='group_invite', schema='profiles', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_profiles_group_invite_token'), table_name='group_invite', schema='profiles')
    op.drop_index(op.f('ix_profiles_group_invite_identity_id'), table_name='group_invite', schema='profiles')
    op.drop_table('group_invite', schema='profiles')
    op.drop_index(op.f('ix_core_client_registration_request_email'), table_name='client_registration_request', schema='core')
    op.drop_table('client_registration_request', schema='core')
    # ### end Alembic commands ###
    # `op.drop_table` doesn't cascade-drop the enum type it implicitly
    # created (same asymmetry as room_permission above) — drop it
    # explicitly so a repeated upgrade/downgrade cycle doesn't collide.
    op.execute("DROP TYPE IF EXISTS client_registration_status")
