"""initial schema

Revision ID: 7cbad58b299d
Revises: 
Create Date: 2026-07-24 04:16:12.851594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cbad58b299d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # One schema per room boundary — core (shared infra), accounts (Task 1),
    # profiles (Task 2), meeting_room (Task 3), tasking (staff task/inbox).
    # Future rooms (Task 4-8) each get their own schema the same way.
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS accounts")
    op.execute("CREATE SCHEMA IF NOT EXISTS profiles")
    op.execute("CREATE SCHEMA IF NOT EXISTS meeting_room")
    op.execute("CREATE SCHEMA IF NOT EXISTS tasking")
    # ltree powers O(log n) ancestor/descendant scope checks on the
    # Task 2 identity tree via a GiST index (see app.core.services.scope_service).
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.Enum('staff', 'client', 'client_staff', 'system', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='core'
    )
    op.create_index(op.f('ix_core_audit_log_action'), 'audit_log', ['action'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_created_at'), 'audit_log', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False, schema='core')
    op.create_table('calendar_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_fired', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_event')),
    schema='core'
    )
    op.create_index(op.f('ix_core_calendar_event_due_at'), 'calendar_event', ['due_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_calendar_event_remind_at'), 'calendar_event', ['remind_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_calendar_event_room'), 'calendar_event', ['room'], unique=False, schema='core')
    # client_user.identity_id -> identity and identity.created_by_client_id
    # -> client_user form a genuine cross-schema circular FK pair (the
    # original codebase's history only avoided this by creating the two
    # tables in separate migrations, staff_user's created_by_client_id
    # column added in a later revision than identity/client_user
    # themselves). Same fix as staff_category/staff_user above: create
    # client_user without this FK inline, add it post-hoc once identity
    # exists (see the create_foreign_key call right after identity below).
    op.create_table('client_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_user')),
    schema='core'
    )
    op.create_index(op.f('ix_core_client_user_email'), 'client_user', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_client_user_identity_id'), 'client_user', ['identity_id'], unique=False, schema='core')
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt')),
    schema='core'
    )
    op.create_index(op.f('ix_core_login_attempt_created_at'), 'login_attempt', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_login_attempt_identifier'), 'login_attempt', ['identifier'], unique=False, schema='core')
    op.create_table('room_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_account')),
    schema='core'
    )
    op.create_index('ix_room_account_room', 'room_account', ['room'], unique=True, schema='core')
    # staff_category.created_by -> staff_user and staff_user.category_id ->
    # staff_category form a genuine circular FK pair — autogenerate emitted
    # both inline, but staff_user doesn't exist yet when staff_category is
    # created. Split staff_category's FK out to a post-hoc
    # create_foreign_key below (same technique as 46cdabe19280's
    # ledger_entry->identity FK in the prior migration history).
    op.create_table('staff_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_category')),
    sa.UniqueConstraint('name', name=op.f('uq_staff_category_name')),
    schema='core'
    )
    op.create_table('staff_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('admin', 'staff', name='staff_tier'), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['core.staff_category.id'], name=op.f('fk_staff_user_category_id_staff_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_user')),
    schema='core'
    )
    op.create_index(op.f('ix_core_staff_user_category_id'), 'staff_user', ['category_id'], unique=False, schema='core')
    op.create_foreign_key(
        op.f('fk_staff_category_created_by_staff_user'),
        'staff_category', 'staff_user',
        ['created_by'], ['id'],
        source_schema='core', referent_schema='core',
        ondelete='SET NULL',
    )
    op.create_index(op.f('ix_core_staff_user_email'), 'staff_user', ['email'], unique=True, schema='core')
    op.create_table('group_code_sequence',
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix', name=op.f('pk_group_code_sequence')),
    schema='profiles'
    )
    op.create_table('identity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('id_type', sa.Enum('group', 'member', name='identity_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_by_client_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_identity_created_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['core.client_user.id'], name=op.f('fk_identity_created_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['profiles.identity.id'], name=op.f('fk_identity_parent_id_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('path', name=op.f('uq_identity_path')),
    schema='profiles'
    )
    op.create_foreign_key(
        op.f('fk_client_user_identity_id_identity'),
        'client_user', 'identity',
        ['identity_id'], ['id'],
        source_schema='core', referent_schema='profiles',
        ondelete='CASCADE',
    )
    op.create_index('ix_identity_path_pattern', 'identity', ['path'], unique=False, schema='profiles', postgresql_ops={'path': 'text_pattern_ops'})
    op.create_index(op.f('ix_profiles_identity_parent_id'), 'identity', ['parent_id'], unique=False, schema='profiles')
    op.create_table('account_registry_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('ai_platform', 'comms_platform', 'payment', 'hosting', 'domain', 'government', 'banking', 'tool', 'other', name='account_category'), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('linked_api', sa.String(length=255), nullable=False),
    sa.Column('documentation_url', sa.String(length=1000), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_account_registry_entry_created_by_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_registry_entry')),
    schema='accounts'
    )
    op.create_table('agent_sub_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_account_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_account_id'], ['core.room_account.id'], name=op.f('fk_agent_sub_account_room_account_id_room_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sub_account')),
    schema='core'
    )
    op.create_index('ix_agent_sub_account_room_agent', 'agent_sub_account', ['room_account_id', 'agent_name'], unique=True, schema='core')
    op.create_table('archive_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('shelf', sa.Enum('operational_library', 'transfer', 'receiving', name='archive_shelf'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'received', 'reviewed', 'accepted', 'rejected', 'active', name='archive_item_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=True),
    sa.Column('target_room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=True),
    sa.Column('approved_for_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['core.staff_user.id'], name=op.f('fk_archive_item_reviewed_by_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_item')),
    schema='core'
    )
    op.create_index(op.f('ix_core_archive_item_room'), 'archive_item', ['room'], unique=False, schema='core')
    op.create_index(op.f('ix_core_archive_item_shelf'), 'archive_item', ['shelf'], unique=False, schema='core')
    op.create_table('client_registration_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='client_registration_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_client_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_client_user_id'], ['core.client_user.id'], name=op.f('fk_client_registration_request_created_client_user_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['core.staff_user.id'], name=op.f('fk_client_registration_request_reviewed_by_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_registration_request')),
    schema='core'
    )
    op.create_index(op.f('ix_core_client_registration_request_email'), 'client_registration_request', ['email'], unique=False, schema='core')
    op.create_table('client_staff_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('created_by_client_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['core.client_user.id'], name=op.f('fk_client_staff_user_created_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_client_staff_user_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_staff_user')),
    schema='core'
    )
    op.create_index(op.f('ix_core_client_staff_user_email'), 'client_staff_user', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_client_staff_user_identity_id'), 'client_staff_user', ['identity_id'], unique=False, schema='core')
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.Enum('funding', 'customer_transfer', 'agent_spend', 'gate_charge', 'adjustment', name='ledger_entry_type'), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audit_log_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['core.audit_log.id'], name=op.f('fk_ledger_entry_audit_log_id_audit_log'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_ledger_entry_identity_id_identity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entry')),
    schema='core'
    )
    op.create_index(op.f('ix_core_ledger_entry_created_at'), 'ledger_entry', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ledger_entry_entry_type'), 'ledger_entry', ['entry_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ledger_entry_identity_id'), 'ledger_entry', ['identity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_ledger_entry_room'), 'ledger_entry', ['room'], unique=False, schema='core')
    op.create_table('llm_usage_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.Enum('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name'), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_llm_usage_record_identity_id_identity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_record')),
    schema='core'
    )
    op.create_index(op.f('ix_core_llm_usage_record_created_at'), 'llm_usage_record', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_llm_usage_record_identity_id'), 'llm_usage_record', ['identity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_llm_usage_record_room'), 'llm_usage_record', ['room'], unique=False, schema='core')
    op.create_table('refresh_token',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('staff_user_id', sa.String(), nullable=True),
    sa.Column('client_user_id', sa.String(), nullable=True),
    sa.Column('client_staff_user_id', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['staff_user_id'], ['core.staff_user.id'], name=op.f('fk_refresh_token_staff_user_id_staff_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    schema='core'
    )
    op.create_index(op.f('ix_core_refresh_token_client_staff_user_id'), 'refresh_token', ['client_staff_user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_refresh_token_client_user_id'), 'refresh_token', ['client_user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_refresh_token_staff_user_id'), 'refresh_token', ['staff_user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True, schema='core')
    op.create_table('conversation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='conversation_status'), nullable=False),
    sa.Column('target_language', sa.String(length=50), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('character_role', sa.String(length=200), nullable=False),
    sa.Column('initiated_by_client_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_conversation_identity_id_identity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by_client_id'], ['core.client_user.id'], name=op.f('fk_conversation_initiated_by_client_id_client_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_conversation_identity_id'), 'conversation', ['identity_id'], unique=False, schema='meeting_room')
    op.create_table('meeting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host_identity_id', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('translate_live', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'completed', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('room_name', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_meeting_created_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_identity_id'], ['profiles.identity.id'], name=op.f('fk_meeting_host_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting')),
    sa.UniqueConstraint('room_name', name=op.f('uq_meeting_room_name')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_meeting_host_identity_id'), 'meeting', ['host_identity_id'], unique=False, schema='meeting_room')
    op.create_table('whatsapp_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_whatsapp_link_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_link')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_whatsapp_link_identity_id'), 'whatsapp_link', ['identity_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_whatsapp_link_phone_number'), 'whatsapp_link', ['phone_number'], unique=True, schema='meeting_room')
    op.create_table('client_org_profile',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('group_code', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=False),
    sa.Column('abn_acnc_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_client_org_profile_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_client_org_profile')),
    sa.UniqueConstraint('group_code', name=op.f('uq_client_org_profile_group_code')),
    schema='profiles'
    )
    op.create_table('consent_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('context', sa.Enum('onboarding', 'record_time', name='consent_context'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('retention_period', sa.String(length=100), nullable=False),
    sa.Column('data_residency', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('captured_by', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['core.staff_user.id'], name=op.f('fk_consent_record_captured_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_consent_record_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_record')),
    schema='profiles'
    )
    op.create_index(op.f('ix_profiles_consent_record_identity_id'), 'consent_record', ['identity_id'], unique=False, schema='profiles')
    op.create_table('group_invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_client_id', sa.String(), nullable=True),
    sa.Column('created_by_staff_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['core.client_user.id'], name=op.f('fk_group_invite_created_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_group_invite_created_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_group_invite_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_invite')),
    schema='profiles'
    )
    op.create_index(op.f('ix_profiles_group_invite_identity_id'), 'group_invite', ['identity_id'], unique=False, schema='profiles')
    op.create_index(op.f('ix_profiles_group_invite_token'), 'group_invite', ['token'], unique=True, schema='profiles')
    op.create_index('uq_group_invite_active_identity', 'group_invite', ['identity_id'], unique=True, schema='profiles', postgresql_where=sa.text('is_active'))
    op.create_table('ilc_group_profile',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('group_code', sa.String(length=32), nullable=False),
    sa.Column('name_hindi', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('date_of_registration', sa.Date(), nullable=True),
    sa.Column('application_signed', sa.Boolean(), nullable=False),
    sa.Column('registered_office', sa.Text(), nullable=False),
    sa.Column('area_of_operation', sa.Text(), nullable=False),
    sa.Column('governing_act', sa.String(length=255), nullable=False),
    sa.Column('registering_authority', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('cooperative_type', sa.String(length=255), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_ilc_group_profile_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_ilc_group_profile')),
    sa.UniqueConstraint('group_code', name=op.f('uq_ilc_group_profile_group_code')),
    schema='profiles'
    )
    op.create_table('ilc_member_roster',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_identity_id', sa.String(), nullable=False),
    sa.Column('ilc_registration_number', sa.String(length=64), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('claimed_by_identity_id', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_client_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_identity_id'], ['profiles.identity.id'], name=op.f('fk_ilc_member_roster_claimed_by_identity_id_identity'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['core.client_user.id'], name=op.f('fk_ilc_member_roster_created_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_identity_id'], ['profiles.identity.id'], name=op.f('fk_ilc_member_roster_group_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ilc_member_roster')),
    schema='profiles'
    )
    op.create_index(op.f('ix_profiles_ilc_member_roster_group_identity_id'), 'ilc_member_roster', ['group_identity_id'], unique=False, schema='profiles')
    op.create_index('uq_ilc_member_roster_group_number', 'ilc_member_roster', ['group_identity_id', 'ilc_registration_number'], unique=True, schema='profiles')
    op.create_table('permission',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('own_registered', sa.Boolean(), nullable=True),
    sa.Column('own_connected', sa.Boolean(), nullable=True),
    sa.Column('own_auto_respond', sa.Boolean(), nullable=True),
    sa.Column('own_send_on', sa.Boolean(), nullable=True),
    sa.Column('own_can_message_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=True),
    sa.Column('own_can_receive_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=True),
    sa.Column('own_credit_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('own_reply_role', sa.String(length=100), nullable=True),
    sa.Column('own_reply_tone', sa.String(length=100), nullable=True),
    sa.Column('own_reply_complexity', sa.String(length=100), nullable=True),
    sa.Column('own_reply_character', sa.String(length=100), nullable=True),
    sa.Column('own_reply_language', sa.String(length=20), nullable=True),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('effective_registered', sa.Boolean(), nullable=False),
    sa.Column('effective_connected', sa.Boolean(), nullable=False),
    sa.Column('effective_auto_respond', sa.Boolean(), nullable=False),
    sa.Column('effective_send_on', sa.Boolean(), nullable=False),
    sa.Column('effective_can_message_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=False),
    sa.Column('effective_can_receive_scope', sa.Enum('none', 'within_tree', 'any', name='permission_scope'), nullable=False),
    sa.Column('effective_credit_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('effective_reply_role', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_tone', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_complexity', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_character', sa.String(length=100), nullable=False),
    sa.Column('effective_reply_language', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_permission_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_permission')),
    schema='profiles'
    )
    op.create_table('profile_account',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_profile_account_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_profile_account')),
    schema='profiles'
    )
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_by_staff_id', sa.String(), nullable=True),
    sa.Column('assigned_to_staff_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'blocked', 'completed', 'cancelled', name='task_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_task_assigned_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_staff_id'], ['core.staff_user.id'], name=op.f('fk_task_assigned_to_staff_id_staff_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    schema='tasking'
    )
    op.create_index(op.f('ix_tasking_task_assigned_to_staff_id'), 'task', ['assigned_to_staff_id'], unique=False, schema='tasking')
    op.create_table('api_monitor_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('linked_account_registry_id', sa.String(), nullable=True),
    sa.Column('credit_remaining', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('usage_current_period', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('health_status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='api_health_status'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_registry_id'], ['accounts.account_registry_entry.id'], name=op.f('fk_api_monitor_entry_linked_account_registry_id_account_registry_entry'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_monitor_entry')),
    schema='accounts'
    )
    op.create_table('financial_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('subscription', 'salary', 'contractor', 'api_usage', 'hosting', 'other', name='financial_record_category'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('incurred_at', sa.Date(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_period', sa.String(length=50), nullable=False),
    sa.Column('linked_account_registry_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_financial_record_created_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_account_registry_id'], ['accounts.account_registry_entry.id'], name=op.f('fk_financial_record_linked_account_registry_id_account_registry_entry'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_record')),
    schema='accounts'
    )
    op.create_table('meeting_participant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('staff_user_id', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(identity_id IS NOT NULL) != (staff_user_id IS NOT NULL)', name=op.f('ck_meeting_participant_one_actor')),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_meeting_participant_identity_id_identity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_room.meeting.id'], name=op.f('fk_meeting_participant_meeting_id_meeting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['core.staff_user.id'], name=op.f('fk_meeting_participant_staff_user_id_staff_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_participant')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_meeting_participant_meeting_id'), 'meeting_participant', ['meeting_id'], unique=False, schema='meeting_room')
    op.create_index('uq_meeting_participant_identity', 'meeting_participant', ['meeting_id', 'identity_id'], unique=True, schema='meeting_room', postgresql_where=sa.text('identity_id IS NOT NULL'))
    op.create_index('uq_meeting_participant_staff', 'meeting_participant', ['meeting_id', 'staff_user_id'], unique=True, schema='meeting_room', postgresql_where=sa.text('staff_user_id IS NOT NULL'))
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('mode', sa.Enum('auto', 'manual', 'adaptive', name='reply_mode'), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=20), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('tone_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_by_staff_id', sa.String(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['meeting_room.conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_message_sent_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_message_conversation_id'), 'message', ['conversation_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_message_created_at'), 'message', ['created_at'], unique=False, schema='meeting_room')
    op.create_table('session_report',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.Enum('session_summary', 'satisfaction_analysis', 'member_summary', name='report_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('generated_by_client_id', sa.String(), nullable=True),
    sa.Column('generated_by_staff_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['meeting_room.conversation.id'], name=op.f('fk_session_report_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_client_id'], ['core.client_user.id'], name=op.f('fk_session_report_generated_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_session_report_generated_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_report')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_session_report_conversation_id'), 'session_report', ['conversation_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_session_report_created_at'), 'session_report', ['created_at'], unique=False, schema='meeting_room')
    op.create_table('member_profile',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('registered_via', sa.String(length=50), nullable=False),
    sa.Column('source_invite_id', sa.String(), nullable=True),
    sa.Column('ilc_roster_entry_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_member_profile_identity_id_identity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ilc_roster_entry_id'], ['profiles.ilc_member_roster.id'], name=op.f('fk_member_profile_ilc_roster_entry_id_ilc_member_roster'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_invite_id'], ['profiles.group_invite.id'], name=op.f('fk_member_profile_source_invite_id_group_invite'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_member_profile')),
    schema='profiles'
    )
    op.create_table('inbox_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_staff_id', sa.String(), nullable=True),
    sa.Column('sender_client_id', sa.String(), nullable=True),
    sa.Column('recipient_staff_id', sa.String(), nullable=True),
    sa.Column('recipient_client_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_task_id', sa.String(), nullable=True),
    sa.Column('related_meeting_id', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(recipient_staff_id IS NOT NULL) != (recipient_client_id IS NOT NULL)', name=op.f('ck_inbox_message_one_recipient')),
    sa.CheckConstraint('(sender_staff_id IS NOT NULL) != (sender_client_id IS NOT NULL)', name=op.f('ck_inbox_message_one_sender')),
    sa.ForeignKeyConstraint(['recipient_client_id'], ['core.client_user.id'], name=op.f('fk_inbox_message_recipient_client_id_client_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_staff_id'], ['core.staff_user.id'], name=op.f('fk_inbox_message_recipient_staff_id_staff_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_meeting_id'], ['meeting_room.meeting.id'], name=op.f('fk_inbox_message_related_meeting_id_meeting'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasking.task.id'], name=op.f('fk_inbox_message_related_task_id_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_client_id'], ['core.client_user.id'], name=op.f('fk_inbox_message_sender_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_staff_id'], ['core.staff_user.id'], name=op.f('fk_inbox_message_sender_staff_id_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_message')),
    schema='tasking'
    )
    op.create_index('ix_inbox_message_recipient_client_unread', 'inbox_message', ['recipient_client_id', 'read_at'], unique=False, schema='tasking')
    op.create_index('ix_inbox_message_recipient_staff_unread', 'inbox_message', ['recipient_staff_id', 'read_at'], unique=False, schema='tasking')
    op.create_index(op.f('ix_tasking_inbox_message_created_at'), 'inbox_message', ['created_at'], unique=False, schema='tasking')
    op.create_table('task_update',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('author_staff_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('progress_status', sa.Enum('open', 'in_progress', 'blocked', 'completed', 'cancelled', name='task_status'), nullable=True),
    sa.Column('is_concern', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_staff_id'], ['core.staff_user.id'], name=op.f('fk_task_update_author_staff_id_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasking.task.id'], name=op.f('fk_task_update_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_update')),
    schema='tasking'
    )
    op.create_index(op.f('ix_tasking_task_update_created_at'), 'task_update', ['created_at'], unique=False, schema='tasking')
    op.create_index(op.f('ix_tasking_task_update_task_id'), 'task_update', ['task_id'], unique=False, schema='tasking')
    op.create_table('meeting_invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_room.meeting.id'], name=op.f('fk_meeting_invite_meeting_id_meeting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['meeting_room.meeting_participant.id'], name=op.f('fk_meeting_invite_participant_id_meeting_participant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_invite')),
    sa.UniqueConstraint('participant_id', name=op.f('uq_meeting_invite_participant_id')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_meeting_invite_meeting_id'), 'meeting_invite', ['meeting_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_meeting_invite_token'), 'meeting_invite', ['token'], unique=True, schema='meeting_room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_room_meeting_invite_token'), table_name='meeting_invite', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_meeting_invite_meeting_id'), table_name='meeting_invite', schema='meeting_room')
    op.drop_table('meeting_invite', schema='meeting_room')
    op.drop_index(op.f('ix_tasking_task_update_task_id'), table_name='task_update', schema='tasking')
    op.drop_index(op.f('ix_tasking_task_update_created_at'), table_name='task_update', schema='tasking')
    op.drop_table('task_update', schema='tasking')
    op.drop_index(op.f('ix_tasking_inbox_message_created_at'), table_name='inbox_message', schema='tasking')
    op.drop_index('ix_inbox_message_recipient_staff_unread', table_name='inbox_message', schema='tasking')
    op.drop_index('ix_inbox_message_recipient_client_unread', table_name='inbox_message', schema='tasking')
    op.drop_table('inbox_message', schema='tasking')
    op.drop_table('member_profile', schema='profiles')
    op.drop_index(op.f('ix_meeting_room_session_report_created_at'), table_name='session_report', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_session_report_conversation_id'), table_name='session_report', schema='meeting_room')
    op.drop_table('session_report', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_message_created_at'), table_name='message', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_message_conversation_id'), table_name='message', schema='meeting_room')
    op.drop_table('message', schema='meeting_room')
    op.drop_index('uq_meeting_participant_staff', table_name='meeting_participant', schema='meeting_room', postgresql_where=sa.text('staff_user_id IS NOT NULL'))
    op.drop_index('uq_meeting_participant_identity', table_name='meeting_participant', schema='meeting_room', postgresql_where=sa.text('identity_id IS NOT NULL'))
    op.drop_index(op.f('ix_meeting_room_meeting_participant_meeting_id'), table_name='meeting_participant', schema='meeting_room')
    op.drop_table('meeting_participant', schema='meeting_room')
    op.drop_table('financial_record', schema='accounts')
    op.drop_table('api_monitor_entry', schema='accounts')
    op.drop_index(op.f('ix_tasking_task_assigned_to_staff_id'), table_name='task', schema='tasking')
    op.drop_table('task', schema='tasking')
    op.drop_table('profile_account', schema='profiles')
    op.drop_table('permission', schema='profiles')
    op.drop_index('uq_ilc_member_roster_group_number', table_name='ilc_member_roster', schema='profiles')
    op.drop_index(op.f('ix_profiles_ilc_member_roster_group_identity_id'), table_name='ilc_member_roster', schema='profiles')
    op.drop_table('ilc_member_roster', schema='profiles')
    op.drop_table('ilc_group_profile', schema='profiles')
    op.drop_index('uq_group_invite_active_identity', table_name='group_invite', schema='profiles', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_profiles_group_invite_token'), table_name='group_invite', schema='profiles')
    op.drop_index(op.f('ix_profiles_group_invite_identity_id'), table_name='group_invite', schema='profiles')
    op.drop_table('group_invite', schema='profiles')
    op.drop_index(op.f('ix_profiles_consent_record_identity_id'), table_name='consent_record', schema='profiles')
    op.drop_table('consent_record', schema='profiles')
    op.drop_table('client_org_profile', schema='profiles')
    op.drop_index(op.f('ix_meeting_room_whatsapp_link_phone_number'), table_name='whatsapp_link', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_whatsapp_link_identity_id'), table_name='whatsapp_link', schema='meeting_room')
    op.drop_table('whatsapp_link', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_meeting_host_identity_id'), table_name='meeting', schema='meeting_room')
    op.drop_table('meeting', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_conversation_identity_id'), table_name='conversation', schema='meeting_room')
    op.drop_table('conversation', schema='meeting_room')
    op.drop_index(op.f('ix_core_refresh_token_token_hash'), table_name='refresh_token', schema='core')
    op.drop_index(op.f('ix_core_refresh_token_staff_user_id'), table_name='refresh_token', schema='core')
    op.drop_index(op.f('ix_core_refresh_token_client_user_id'), table_name='refresh_token', schema='core')
    op.drop_index(op.f('ix_core_refresh_token_client_staff_user_id'), table_name='refresh_token', schema='core')
    op.drop_table('refresh_token', schema='core')
    op.drop_index(op.f('ix_core_llm_usage_record_room'), table_name='llm_usage_record', schema='core')
    op.drop_index(op.f('ix_core_llm_usage_record_identity_id'), table_name='llm_usage_record', schema='core')
    op.drop_index(op.f('ix_core_llm_usage_record_created_at'), table_name='llm_usage_record', schema='core')
    op.drop_table('llm_usage_record', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_room'), table_name='ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_identity_id'), table_name='ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_entry_type'), table_name='ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_ledger_entry_created_at'), table_name='ledger_entry', schema='core')
    op.drop_table('ledger_entry', schema='core')
    op.drop_index(op.f('ix_core_client_staff_user_identity_id'), table_name='client_staff_user', schema='core')
    op.drop_index(op.f('ix_core_client_staff_user_email'), table_name='client_staff_user', schema='core')
    op.drop_table('client_staff_user', schema='core')
    op.drop_index(op.f('ix_core_client_registration_request_email'), table_name='client_registration_request', schema='core')
    op.drop_table('client_registration_request', schema='core')
    op.drop_index(op.f('ix_core_archive_item_shelf'), table_name='archive_item', schema='core')
    op.drop_index(op.f('ix_core_archive_item_room'), table_name='archive_item', schema='core')
    op.drop_table('archive_item', schema='core')
    op.drop_index('ix_agent_sub_account_room_agent', table_name='agent_sub_account', schema='core')
    op.drop_table('agent_sub_account', schema='core')
    op.drop_table('account_registry_entry', schema='accounts')
    op.drop_constraint(op.f('fk_client_user_identity_id_identity'), 'client_user', schema='core', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_identity_parent_id'), table_name='identity', schema='profiles')
    op.drop_index('ix_identity_path_pattern', table_name='identity', schema='profiles', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_table('identity', schema='profiles')
    op.drop_table('group_code_sequence', schema='profiles')
    op.drop_constraint(op.f('fk_staff_category_created_by_staff_user'), 'staff_category', schema='core', type_='foreignkey')
    op.drop_index(op.f('ix_core_staff_user_email'), table_name='staff_user', schema='core')
    op.drop_index(op.f('ix_core_staff_user_category_id'), table_name='staff_user', schema='core')
    op.drop_table('staff_user', schema='core')
    op.drop_table('staff_category', schema='core')
    op.drop_index('ix_room_account_room', table_name='room_account', schema='core')
    op.drop_table('room_account', schema='core')
    op.drop_index(op.f('ix_core_login_attempt_identifier'), table_name='login_attempt', schema='core')
    op.drop_index(op.f('ix_core_login_attempt_created_at'), table_name='login_attempt', schema='core')
    op.drop_table('login_attempt', schema='core')
    op.drop_index(op.f('ix_core_client_user_identity_id'), table_name='client_user', schema='core')
    op.drop_index(op.f('ix_core_client_user_email'), table_name='client_user', schema='core')
    op.drop_table('client_user', schema='core')
    op.drop_index(op.f('ix_core_calendar_event_room'), table_name='calendar_event', schema='core')
    op.drop_index(op.f('ix_core_calendar_event_remind_at'), table_name='calendar_event', schema='core')
    op.drop_index(op.f('ix_core_calendar_event_due_at'), table_name='calendar_event', schema='core')
    op.drop_table('calendar_event', schema='core')
    op.drop_index(op.f('ix_core_audit_log_entity_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_created_at'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_actor_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_action'), table_name='audit_log', schema='core')
    op.drop_table('audit_log', schema='core')
    # ### end Alembic commands ###

    # Not dropping the `core` schema itself: alembic's own version-tracking
    # table lives there (`version_table_schema="core"` in env.py) — CASCADE-
    # dropping it out from under alembic mid-migration breaks its own
    # bookkeeping UPDATE immediately after this function returns. The
    # individual `op.drop_table` calls above already remove every core
    # table this migration created; `core` itself is left as an empty
    # schema (plus alembic_version) rather than removed.
    op.execute("DROP SCHEMA IF EXISTS tasking CASCADE")
    op.execute("DROP SCHEMA IF EXISTS meeting_room CASCADE")
    op.execute("DROP SCHEMA IF EXISTS profiles CASCADE")
    op.execute("DROP SCHEMA IF EXISTS accounts CASCADE")
    op.execute("DROP EXTENSION IF EXISTS ltree")
