"""add daily reply cap to permission

Revision ID: 9709d283d9be
Revises: af8a0858664e
Create Date: 2026-08-11 08:18:29.451146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9709d283d9be'
down_revision: Union[str, None] = 'af8a0858664e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('own_daily_reply_cap', sa.Integer(), nullable=True), schema='profiles')
    op.add_column('permission', sa.Column('effective_daily_reply_cap', sa.Integer(), nullable=True), schema='profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'effective_daily_reply_cap', schema='profiles')
    op.drop_column('permission', 'own_daily_reply_cap', schema='profiles')
    # ### end Alembic commands ###
