"""add webhook_log table

Revision ID: af8a0858664e
Revises: 7cbad58b299d
Create Date: 2026-08-05 00:06:06.740727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af8a0858664e'
down_revision: Union[str, None] = '7cbad58b299d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # room_name already exists (created by the initial migration) — the
    # generic sa.Enum(create_type=False) kwarg is silently dropped (it's
    # not a real attribute on that class), so this must use the
    # postgresql-dialect ENUM class, which actually honors it.
    room_name_enum = postgresql.ENUM(
        'accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data',
        name='room_name', create_type=False,
    )
    op.create_table('webhook_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', room_name_enum, nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='webhook_direction'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_log')),
    schema='core'
    )
    op.create_index(op.f('ix_core_webhook_log_created_at'), 'webhook_log', ['created_at'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_webhook_log_created_at'), table_name='webhook_log', schema='core')
    op.drop_table('webhook_log', schema='core')
    # ### end Alembic commands ###
