"""comms room config, analysis fields, session reports

Revision ID: bda30688bcff
Revises: e3858b2634f0
Create Date: 2026-07-13 14:33:59.207557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bda30688bcff'
down_revision: Union[str, None] = 'e3858b2634f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_report',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.Enum('session_summary', 'satisfaction_analysis', name='report_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('generated_by_client_id', sa.String(), nullable=True),
    sa.Column('generated_by_staff_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['meeting_room.conversation.id'], name=op.f('fk_session_report_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_client_id'], ['core.client_user.id'], name=op.f('fk_session_report_generated_by_client_id_client_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_session_report_generated_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_report')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_session_report_conversation_id'), 'session_report', ['conversation_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_session_report_created_at'), 'session_report', ['created_at'], unique=False, schema='meeting_room')
    op.add_column('conversation', sa.Column('target_language', sa.String(length=50), nullable=False), schema='meeting_room')
    op.add_column('conversation', sa.Column('tone', sa.String(length=50), nullable=False), schema='meeting_room')
    op.add_column('conversation', sa.Column('character_name', sa.String(length=100), nullable=False), schema='meeting_room')
    op.add_column('conversation', sa.Column('character_role', sa.String(length=200), nullable=False), schema='meeting_room')
    op.add_column('conversation', sa.Column('initiated_by_client_id', sa.String(), nullable=True), schema='meeting_room')
    op.create_foreign_key(op.f('fk_conversation_initiated_by_client_id_client_user'), 'conversation', 'client_user', ['initiated_by_client_id'], ['id'], source_schema='meeting_room', referent_schema='core', ondelete='SET NULL')
    op.add_column('message', sa.Column('tone_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='meeting_room')
    op.add_column('message', sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='meeting_room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'key_points', schema='meeting_room')
    op.drop_column('message', 'tone_analysis', schema='meeting_room')
    op.drop_constraint(op.f('fk_conversation_initiated_by_client_id_client_user'), 'conversation', schema='meeting_room', type_='foreignkey')
    op.drop_column('conversation', 'initiated_by_client_id', schema='meeting_room')
    op.drop_column('conversation', 'character_role', schema='meeting_room')
    op.drop_column('conversation', 'character_name', schema='meeting_room')
    op.drop_column('conversation', 'tone', schema='meeting_room')
    op.drop_column('conversation', 'target_language', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_session_report_created_at'), table_name='session_report', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_session_report_conversation_id'), table_name='session_report', schema='meeting_room')
    op.drop_table('session_report', schema='meeting_room')
    # ### end Alembic commands ###
