"""llm usage tracking

Revision ID: e3858b2634f0
Revises: fab18ab44bdf
Create Date: 2026-07-12 21:37:59.352107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e3858b2634f0'
down_revision: Union[str, None] = 'fab18ab44bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', postgresql.ENUM('accounts', 'profiles', 'meeting_room', 'initial_tasking', 'specialise', 'resources', 'assets', 'hold_data', name='room_name', create_type=False), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_llm_usage_record_identity_id_identity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_record')),
    schema='core'
    )
    op.create_index(op.f('ix_core_llm_usage_record_created_at'), 'llm_usage_record', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_llm_usage_record_identity_id'), 'llm_usage_record', ['identity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_llm_usage_record_room'), 'llm_usage_record', ['room'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_llm_usage_record_room'), table_name='llm_usage_record', schema='core')
    op.drop_index(op.f('ix_core_llm_usage_record_identity_id'), table_name='llm_usage_record', schema='core')
    op.drop_index(op.f('ix_core_llm_usage_record_created_at'), table_name='llm_usage_record', schema='core')
    op.drop_table('llm_usage_record', schema='core')
    # ### end Alembic commands ###
