"""meeting room tables

Revision ID: fab18ab44bdf
Revises: 46cdabe19280
Create Date: 2026-07-10 07:18:16.228202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab18ab44bdf'
down_revision: Union[str, None] = '46cdabe19280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate diffs table/column structure, not enum *values* — this
    # addition (used by core.gate_service for a paid action past the
    # base Meeting Room reply) has to be added by hand.
    # Postgres enum types created by SQLAlchemy live in `public` by
    # default, not the schema of the table that uses them (no
    # inherit_schema=True was set) — confirmed against the live DB.
    op.execute("ALTER TYPE ledger_entry_type ADD VALUE IF NOT EXISTS 'gate_charge'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='conversation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_conversation_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_conversation_identity_id'), 'conversation', ['identity_id'], unique=False, schema='meeting_room')
    op.create_table('meeting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host_identity_id', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('translate_live', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.staff_user.id'], name=op.f('fk_meeting_created_by_staff_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_identity_id'], ['profiles.identity.id'], name=op.f('fk_meeting_host_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_meeting_host_identity_id'), 'meeting', ['host_identity_id'], unique=False, schema='meeting_room')
    op.create_table('whatsapp_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['profiles.identity.id'], name=op.f('fk_whatsapp_link_identity_id_identity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_link')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_whatsapp_link_identity_id'), 'whatsapp_link', ['identity_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_whatsapp_link_phone_number'), 'whatsapp_link', ['phone_number'], unique=True, schema='meeting_room')
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('mode', sa.Enum('auto', 'manual', 'adaptive', name='reply_mode'), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=20), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('sent_by_staff_id', sa.String(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['meeting_room.conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_staff_id'], ['core.staff_user.id'], name=op.f('fk_message_sent_by_staff_id_staff_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    schema='meeting_room'
    )
    op.create_index(op.f('ix_meeting_room_message_conversation_id'), 'message', ['conversation_id'], unique=False, schema='meeting_room')
    op.create_index(op.f('ix_meeting_room_message_created_at'), 'message', ['created_at'], unique=False, schema='meeting_room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_room_message_created_at'), table_name='message', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_message_conversation_id'), table_name='message', schema='meeting_room')
    op.drop_table('message', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_whatsapp_link_phone_number'), table_name='whatsapp_link', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_whatsapp_link_identity_id'), table_name='whatsapp_link', schema='meeting_room')
    op.drop_table('whatsapp_link', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_meeting_host_identity_id'), table_name='meeting', schema='meeting_room')
    op.drop_table('meeting', schema='meeting_room')
    op.drop_index(op.f('ix_meeting_room_conversation_identity_id'), table_name='conversation', schema='meeting_room')
    op.drop_table('conversation', schema='meeting_room')
    # ### end Alembic commands ###
